#!/usr/bin/env bash
# sets up a new 404 error page

# Update package information
sudo apt-get update

# Install the Nginx web server
sudo apt-get install -y nginx

# Create and move content to index.html
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# Create and move content to custom 404.html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Configure Nginx server block
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   # Redirect location
   location /redirect_me {
      return 301 https://www.github.com/codyngpriest;
   }

   # Custom 404 error page
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default

# Move and replace the Nginx default site configuration
sudo mv -f default /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
