#!/usr/bin/env bash
# install a new Nginx web server, and configure it so that its HTTP response contains a custom header
# name of the custom HTTP header must be X-Served-By
# value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update the package list
apt-get update

# Install Nginx
apt-get -y install nginx

# Configure Nginx to add the custom header
sed -i '/server_name _;/a\\tadd_header X-Served-By "$HOSTNAME";' /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx start
