#!/usr/bin/env bash
# Install haproxy
FOO="\
frontend load_balancer
    bind *:80
    mode http
    default_backend foo
    
backend foo
    balance roundrobin
    server 309578-web-01 54.237.84.30:80 check
    server 309578-web-02 34.239.248.85:80 check
"

# Update the package list to ensure you have the latest information about available packages
apt-get -y update

# Install required packages
apt-get -y install software-properties-common

# Add the HAProxy repository and install HAProxy 2.0
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy

# Add your HAProxy configuration to haproxy.cfg
echo "$FOO" >> /etc/haproxy/haproxy.cfg

# Start the HAProxy service
service haproxy start
